### ISSUE TITLE
show more than 9 past activities

### ISSUE THREAD

**Issue by yotam66** [aradmargalit/milameter#104]
At the moment, although it says I have 15 activities uploaded (which I think is not accurate, should be about 11), I can only see the 9 that you see in the image. Can we see all of them, and can they be shown in smaller tiles or icons?

![image](https://user-images.githubusercontent.com/73128339/236867036-ae8e8074-e7fa-4de0-ab31-1ad769d46af9.png)

**Comment by aradmargalit** [comment]
I agree this is confusing. Here's what's happening:
1. You do have 15 _Garmin_ activities uploaded to your browser
2. Milameter is showing you 9 Strava activities, of which 6 overlap with your 15 Garmin Activities

I think what you're really asking for here is pagination, or some sort of "infinite scroll" where you can go as far back in time as you'd like. Is that right?

**Comment by yotam66** [comment]
That is right. Thanks. YMSent from my iPhoneOn May 8, 2023, at 8:58 AM, Arad Margalit ***@***.***> wrote:﻿
I agree this is confusing. Here's what's happening:

You do have 15 Garmin activities uploaded to your browser
Milameter is showing you 9 Strava activities, of which 6 overlap with your 15 Garmin Activities

I think what you're really asking for here is pagination, or some sort of "infinite scroll" where you can go as far back in time as you'd like. Is that right?

**Comment by aradmargalit** [comment]
@eshedmargalit I think this is as "easy" 😉 as added pagination on scroll. We can hard limit to some reasonable amount (100?) activities. If perf suffers, we can virtualize the scrollable surface area.
