### ISSUE TITLE
Make Mila’s track a solid line, as opposed to a dashed line.

### ISSUE THREAD

**Issue by yotam66** [aradmargalit/milameter#57]
It’s hard to see the path when not zoomed in

**Comment by aradmargalit** [comment]
@yotam66 

We struggled with this a bit in development. Because so much of the run is “together” two solid lines mean the bottom layer is blocked.

Maybe this is part of a bigger feature around supporting a better zoomed-in experience, where the dashes adapt to the zoom level?
