### ISSUE TITLE
Add Mila .fit save option

### ISSUE THREAD

**Issue by yotam66** [aradmargalit/milameter#63]
so I can go look at old runs without connecting and uploading from her watch.

**Comment by aradmargalit** [comment]
I like this idea. From what I can tell, a Garmin file is about 10KB per mile, and browsers can hold on to about 4MB per user, which means we could cache around 400 miles-worth of runs.

**Comment by aradmargalit** [comment]
@yotam66 , how do you see this working with the Strava runs? Right now we only show the most recent 9.
