### ISSUE TITLE
add more vertical space for the text on total elevation gain for dog

### ISSUE THREAD

**Issue by yotam66** [aradmargalit/milameter#74]
See image. On my screen Total Elevation Gain for dog get wrapped and the value is closer to the edge of the zone.

![image](https://user-images.githubusercontent.com/73128339/225775684-121ca40d-cfd1-407d-89bf-36b2024d6cf6.png)

**Comment by eshedmargalit** [comment]
This may be fixed by #79 , since it changes "Total Elevation Gain" to "Elevation Gain" and won't push text onto a 3rd line

**Comment by aradmargalit** [comment]
This is fixed now
